# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

predict1d <- function(XY_mat, X_pred, kcode, h) {
    .Call(`_LoclinRcpp_predict1d`, XY_mat, X_pred, kcode, h)
}

multi <- function(Z, Y, X_pred, kcode, h) {
    .Call(`_LoclinRcpp_multi`, Z, Y, X_pred, kcode, h)
}

predict1dd <- function(X, Y, X_pred, kcode, h) {
    .Call(`_LoclinRcpp_predict1dd`, X, Y, X_pred, kcode, h)
}

bin1d <- function(X, Y, X_pred, kcode, h, bins) {
    .Call(`_LoclinRcpp_bin1d`, X, Y, X_pred, kcode, h, bins)
}

loclin <- function(XY_mat, method, kcode, epsilon, h, N_min) {
    .Call(`_LoclinRcpp_loclin`, XY_mat, method, kcode, epsilon, h, N_min)
}

predict <- function(XY_mat, X_mat, method, kcode, epsilon, h, N_min) {
    .Call(`_LoclinRcpp_predict`, XY_mat, X_mat, method, kcode, epsilon, h, N_min)
}

bw_loocv <- function(XY_mat, method, kcode, epsilon, bw, N_min) {
    .Call(`_LoclinRcpp_bw_loocv`, XY_mat, method, kcode, epsilon, bw, N_min)
}

csmoothmean <- function(x, z, w, h, kernel, d, newx) {
    .Call(`_LoclinRcpp_csmoothmean`, x, z, w, h, kernel, d, newx)
}

