# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

llr1d_cpp <- function(X, Y, X_pred, kcode, h, wt) {
    .Call(`_llrRcpp_llr1d_cpp`, X, Y, X_pred, kcode, h, wt)
}

llr2d_cpp <- function(X, Y, X_pred, kcode, h, wt) {
    .Call(`_llrRcpp_llr2d_cpp`, X, Y, X_pred, kcode, h, wt)
}

llr_cpp <- function(X, Y, X_pred, kcode, h, wt) {
    .Call(`_llrRcpp_llr_cpp`, X, Y, X_pred, kcode, h, wt)
}

bin1d_cpp <- function(X, Y, bins, wt) {
    .Call(`_llrRcpp_bin1d_cpp`, X, Y, bins, wt)
}

bin2d_cpp <- function(X, Y, bins, wt) {
    .Call(`_llrRcpp_bin2d_cpp`, X, Y, bins, wt)
}

llrt_cpp <- function(X, Y, X_pred, wt, method, kcode, epsilon, h, N_min) {
    .Call(`_llrRcpp_llrt_cpp`, X, Y, X_pred, wt, method, kcode, epsilon, h, N_min)
}

tgcv_cpp <- function(X, Y, wt, method, kcode, epsilon, bw, N_min) {
    .Call(`_llrRcpp_tgcv_cpp`, X, Y, wt, method, kcode, epsilon, bw, N_min)
}

approx_gcv_cpp <- function(X, Y, wt, method, kcode, epsilon, bw, N_min) {
    .Call(`_llrRcpp_approx_gcv_cpp`, X, Y, wt, method, kcode, epsilon, bw, N_min)
}

#' Get number of processors
#' @return number of processors 
#' @export
get_num_procs <- function() {
    .Call(`_llrRcpp_get_num_procs`)
}

#' Set number of threads to use 
#' @param threads number of threads to use 
#' @return number of threads set 
#' @export
set_num_threads <- function(threads) {
    .Call(`_llrRcpp_set_num_threads`, threads)
}

