# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loclin <- function(XY_mat, method, kcode, epsilon, h, N_min) {
    .Call(`_LoclinRcpp_loclin`, XY_mat, method, kcode, epsilon, h, N_min)
}

predict <- function(XY_mat, X_mat, method, kcode, epsilon, h, N_min) {
    .Call(`_LoclinRcpp_predict`, XY_mat, X_mat, method, kcode, epsilon, h, N_min)
}

bw_loocv <- function(XY_mat, method, kcode, epsilon, bw, N_min) {
    .Call(`_LoclinRcpp_bw_loocv`, XY_mat, method, kcode, epsilon, bw, N_min)
}

